### ISSUE TITLE
Week 10/11-10/16

### ISSUE THREAD

**Issue by kevindavison123** [kevindavison123/EventApp#3]
Now we are going to get into more of the back end of the app.
-Creating a Database and server to host it on
-Connecting that database and server to the app.
-Dynamically creating image buttons from the submit form button.
-Dynamically creating the description page from the submit form button. 
We will discuss Monday how to divide this up.

**Comment by liamlundy** [comment]
I'll set up the backend. We'll be using Dropwizard as our REST API. http://www.dropwizard.io/ for more info.
